name: Synchronize PR Milestone
on:
   pull_request_target:
      branches:
         - "master"
         - "[0-9]+.[0-9]+.z"
         - "data-migration-5.3"
      types:
         - milestoned
         - demilestoned
jobs:
   synchronize-pr-milestone:
      runs-on: ubuntu-latest
      steps:
         - uses: actions/checkout@v4
         - name: Copy milestone to other PR
           run: |
              SOURCE_REPO="${{ github.repository }}"
              SOURCE_PR="${{ github.event.pull_request.number }}"
              CONTENT="$(gh pr view "$SOURCE_PR" --json "body,comments" -q '.body, .comments[].body')"
              
              while read -r line; do
                if [[ $line =~ Closes\ ([^/]+/[^/]+)#([0-9]+) ]]; then
                  TARGET_REPO="${BASH_REMATCH[1]}"
                  TARGET_PR="${BASH_REMATCH[2]}"
                  .github/workflows/common-synchronize-pr-milestone.sh $SOURCE_REPO $SOURCE_PR $TARGET_REPO $TARGET_PR
                fi
              done <<< "$CONTENT"
           env:
              GH_TOKEN: ${{ secrets.DEVOPSHAZELCAST_PAT_FOR_MONOREPO }}
